### PR TITLE
Updated Readme file and added installation instructions for Scoop

### PR DESCRIPTION
**Pull request by simonsan**
- Updated Readme and License file to markdown for better readability on Github
- Added instructions for Installation via **Scoop**: https://github.com/Calinou/scoop-games/pull/226

Preview of the Readme can be seen here: https://github.com/simonsan/AGE

### CODE REVIEW

**Comment by Tapsa** [comment]
Thanks for formatting the readme. I suppose .md is required by GitHub to show the contents well formatted, but is there reason that file extension needs to be gone from the LICENSE file? Remember that this is still designed as Windows app, and just happens to be buildable on Linux.

Where does scoop get the build to install?

**Comment by simonsan** [comment]
> Thanks for formatting the readme. I suppose .md is required by GitHub to show the contents well formatted, but is there reason that file extension needs to be gone from the LICENSE file? Remember that this is still designed as Windows app, and just happens to be buildable on Linux.

The license file i renamed and changed to LICENSE because it's standing out more as the license inside a github repository and get's special threatment by IDEs. For example VSCode is marking it with a key symbol to easier distinguish from other files. Not a big change, can change it back if you like.

> Where does scoop get the build to install?
I asked that again in the PR, it's getting it from a google docs export which could be a mirror of aokheaven or a self-built binary, not sure. But will keep you updated. It checks the version automatically with aokheaven though.

**Comment by Tapsa** [comment]
The installation part should at least have a disclaimer that I (repository owner) am not collaborating with scoop and a mention that updates can be manually downloaded from https://aok.heavengames.com/blacksmith/showfile.php?fileid=11002

Better title would be:
A program for editing data files of Age of Empires, Age of Empires II, Star Wars: Galactic Battlegrounds, their expansions, upgrades, and mods.

I've been thinking of adding releases here straight in GitHub.

**Comment by simonsan** [comment]
> The installation part should at least have a disclaimer that I (repository owner) am not collaborating with scoop and a mention that updates can be manually downloaded from https://aok.heavengames.com/blacksmith/showfile.php?fileid=11002

> Better title would be:
> A program for editing data files of Age of Empires, Age of Empires II, Star Wars: Galactic Battlegrounds, their expansions, upgrades, and mods.

Will add that both.

 
> I've been thinking of adding releases here straight in GitHub.

Yeah, Continous Integration with Github Actions and automatic pushing artifacts to the release section would be nice. I can support you with that, if you haven't worked with Github actions before. The Scoop packages could then come directly from here for example.

**Comment by Tapsa** [comment]
Thanks! I think continuous integration is overkill for this project, but if you know something about releases that can be downloaded from here, that'd be great.

**Pull request merged**
