### PR TITLE
A lot of fixes and a couple of new features.

### PR DESCRIPTION
**Pull request by sandsmark**

### CODE REVIEW

**Comment by sandsmark** [comment]
In case you're still interested; fixed some more issues on linux, added support for importing PNGs to 8-bit SLPs, updated/new README, new icons, viewing of the colors in the color tab (was kind of hard to guess earlier), and some other stuff I don't remember.

**Comment by sandsmark** [comment]
The new icons, I think they look a bit more modern at least:

image

**Comment by sandsmark** [comment]
and just a fun fact/interesting thing (don't know where else to put it, so whatever); Microsoft now ships both AGE and genieutils with AoE 2 Definitive Edition (not sure if they did with aoe1 de).

**Comment by Tapsa** [comment]
I don't know why I have not received any email notifications about your recent comments. As you can see, the build included in II DE does not include pretty much if any of your work.

**Comment by Tapsa** [comment]
Your branch has started to live its own life. You gave me many good ideas though. Thanks man.

**Pull request closed without merging**
